# Generated by Django 5.2.17 on 2026-09-16 07:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays Only'), ('target_days_per_week', 'Target Days Per Week'), ('custom', 'Custom')], default='daily', max_length=30)),
                ('target_days_per_week', models.PositiveIntegerField(blank=True, default=7, null=True)),
                ('type', models.CharField(choices=[('boolean', 'Yes/No (Check-off)'), ('numeric', 'Numeric Target')], default='boolean', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('preferred_time_window', models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='anytime', max_length=30)),
                ('color_hex', models.CharField(default='#10B981', max_length=7)),
                ('icon', models.CharField(default='check-circle', max_length=50)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'db_table': 'habits',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('log_date', models.DateField()),
                ('logged_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('is_frozen', models.BooleanField(default=False)),
                ('friction_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit Log',
                'verbose_name_plural': 'Habit Logs',
                'db_table': 'habit_logs',
                'ordering': ['-log_date', '-created_at'],
                'unique_together': {('habit', 'log_date')},
            },
        ),
    ]
