# Generated by Django 5.2.17 on 2026-09-18 18:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('stream_type', models.CharField(choices=[('salary', 'Primary Salary / W2'), ('freelance', 'Freelance & Contracting'), ('business', 'Business & SaaS Revenue'), ('investment', 'Dividends & Capital Gains'), ('rental', 'Rental & Real Estate'), ('other', 'Other Inflow')], default='salary', max_length=30)),
                ('color_hex', models.CharField(default='#10B981', max_length=7)),
                ('icon', models.CharField(default='briefcase', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income Source',
                'verbose_name_plural': 'Income Sources',
                'db_table': 'income_sources',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount_base_currency_cents', models.BigIntegerField(default=0)),
                ('received_date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.CharField(choices=[('none', 'One-time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('payer_name', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='income.incomesource')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'db_table': 'incomes',
                'ordering': ['-received_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-received_date'], name='incomes_user_id_6d6896_idx'), models.Index(fields=['source', '-received_date'], name='incomes_source__5c26b4_idx')],
            },
        ),
    ]
